<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Form Field Clear</title>
      <script type="text/javascript"  src='../../../../libuser/toitldocumentdomain.js'></script>
      <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css"
            rel="stylesheet" type="text/css"/>
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.js"></script>
      <script type="text/javascript">
         $(document).ready(function() {
            $('#detailID')
            .dialog({
               autoOpen: true,
               width: 600,
               height: 400,
               position: 'center',
               resizable: true,
               draggable: true });
         });
      </script>
   </head>
   <body>
      <h1>PÁGINA RELATÓRIO PERíODO</h1>
      <div id="detailID" style="overflow:scroll">
         <iframe  style="width:100%;height:100%;"
                  src="/public/periodo.pdf">

         </iframe>
      </div>
   </body>
</html>