<span class="label">Empresa-Aluno</span>
<br />
<a href="/empresaAluno/index/add/">Criar novo...</a>
<br />
<br />
<?php if (count($this->data) > 0): ?>
<table width="500" border="1">
  <tr>
    <td width="50" align="center" style="padding:5px;"><b>Empresa</b></td>
    <td width="50" align="center" style="padding:5px;"><b>Aluno</b></td>
    <td width="180" align="center" colspan="2"><b>OPÇÕES</b></td>
  </tr>
<?php foreach ($this->data as $d): ?>
  <tr>
    <td width="50" align="center" style="padding:5px;"><?php echo $d['emp_codigo']; ?></td>
    <td width="50" align="center" style="padding:5px;"><?php echo $d['alu_codigo']; ?></td>
    <td width="90" align="center">
       <a href="/empresaAluno/index/add/idEmpresa/<?php echo $d['emp_codigo']; ?>/idAluno/<?php echo $d['alu_codigo']; ?>">
          Atualizar
       </a>
    </td>
    <td width="90" align="center">
       <a href="/empresaAluno/index/delete/idEmpresa/<?php echo $d['emp_codigo']; ?>/idAluno/<?php echo $d['alu_codigo']; ?>">
          Excluir
       </a>
    </td>
  </tr>
<?php endforeach; ?>
</table>
<br />
<?php echo $this->data; ?>
<?php endif; ?>
