<h1>Produto Index Action</h1>
<br />
<a href="/produto/index/add/">Criar novo Produto</a>
<br />
<br />
<?php if (count($this->data) > 0): ?>
<table width="500" border="1">
  <tr>
    <td width="50" align="center" style="padding:5px;"><b>Codigo</b></td>
    <td width="50" align="center" style="padding:5px;"><b>Compras</b></td>
    <td width="270" align="center" style="padding:5px;"><b>Prazo Pagto</b></td>
    <td width="50" align="center" style="padding:5px;"><b>Preço Venda</b></td>
    <td width="50" align="center" style="padding:5px;"><b>Prazo Recebimento</b></td>
    <td width="50" align="center" style="padding:5px;"><b>Propaganda</b></td>
    <td width="50" align="center" style="padding:5px;"><b>Tipo</b></td>
    <td width="180" align="center" colspan="2"><b>OPÇÕES</b></td>
  </tr>
<?php foreach ($this->data as $d): ?>
  <tr>
    <td width="50" align="center" style="padding:5px;"><?php echo $d['pro_codigo']; ?></td>
    <td width="50" align="center" style="padding:5px;"><?php echo $d['pro_compras']; ?></td>
    <td width="270" style="padding:5px;"><?php echo $d['pro_prazopagto']; ?></td>
    <td width="270" style="padding:5px;"><?php echo $d['pro_precovenda']; ?></td>
    <td width="270" style="padding:5px;"><?php echo $d['pro_prazorecebimento']; ?></td>
    <td width="270" style="padding:5px;"><?php echo $d['pro_propaganda']; ?></td>
    <td width="270" style="padding:5px;"><?php echo $d['pro_tipo']; ?></td>
    <td width="90" align="center"><a href="/produto/index/add/id/<?php echo $d['pro_codigo']; ?>">Atualizar</a></td>
    <td width="90" align="center"><a href="/produto/index/delete/id/<?php echo $d['pro_codigo']; ?>">Excluir</a></td>
  </tr>
<?php endforeach; ?>
</table>
<br />
<?php echo $this->data; ?>
<?php endif; ?>
